LearningPlatform/LearningPlatform/Controllers/AuthenticationController.cs
using System.Linq;

using AutoMapper;

using LearningPlatform.Common.DTOs.Requests;
using LearningPlatform.Common.DTOs.ViewModels;
using LearningPlatform.Constants;
using LearningPlatform.Identity;
using LearningPlatform.Identity.Authentication;
using LearningPlatform.Services.Interfaces;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LearningPlatform.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IMapper mapper;
        private readonly IUserService userService;

        private readonly IJwtAuthenticationManager authManager;
        private readonly IAuthorizationHelper authorizationHelper;

        public AuthenticationController(IMapper mapper, IUserService userService, IJwtAuthenticationManager authManager, IAuthorizationHelper authorizationHelper)
        {
            this.mapper = mapper;
            this.userService = userService;

            this.authManager = authManager;
            this.authorizationHelper = authorizationHelper;
        }

        [Authorize]
        [AllowAnonymous]
        [HttpPost("authenticate")]
        public IActionResult Authenticate(UserCred userCred)
        {
            var token = authManager.Authenticate(userCred, userService);

            if (token == null)
            {
                return Unauthorized();
            }

            this.HttpContext.Session.SetString("JWToken", token);

            return Ok(token);
        }

        public IActionResult Register()
        {
            var viewModel = new RegisterViewModel();

            return View(model: viewModel);
        }

        [HttpPost]
        public IActionResult Register(RegisterViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(model: viewModel);
            }

            if (viewModel.Password != viewModel.ConfirmPassword)
            {
                ModelState.AddModelError("ConfirmPassword", AuthenticationMessages.MissmatchingPasswords);

                return View(model: viewModel);
            }

            var userExist = userService.UserExists(viewModel.Email);

            if (userExist)
            {
                ModelState.AddModelError("Email", AuthenticationMessages.AlreadyTakenEmail);

                return View(model: viewModel);
            }

            var user = mapper.Map<UserRequestDto>(viewModel);
            this.userService.Create(user);

            this.TempData["Message"] = AuthenticationMessages.SuccessfulRegistration;
            return RedirectToAction(controllerName: "home", actionName: "index");
        }

        [HttpGet]
        public IActionResult Login()
        {
            var viewModel = new LoginViewModel();

            return View(model: viewModel);
        }

        [HttpPost]
        public IActionResult Login([FromForm] LoginViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(model: viewModel);
            }

            var userCred = mapper.Map<UserCred>(viewModel);

            Authenticate(userCred);

            var token = HttpContext.Session.GetString("JWToken");

            if (string.IsNullOrEmpty(token))
            {
                TempData["Message"] = AuthenticationMessages.WrongCredentials;
                return View();
            }

            var user = authorizationHelper.GetUserFromToken(HttpContext);

            HttpContext.Session.SetString("CurrentUser", user.FirstName);
            TempData["Message"] = string.Format(AuthenticationMessages.LoggedIn, user.FirstName);

            if (user.Role == Models.Enums.Role.Teacher)
            {
                return RedirectToAction(actionName: "Index", controllerName: "Course");
            }

            return RedirectToAction(actionName: "ProfilePage", controllerName: "User", new { id = user.Id });
        }

        [HttpGet("logout")]
        public IActionResult Logout()
        {
            this.HttpContext.Session.Remove("CurrentUser");
            this.HttpContext.Session.Remove("JWToken");
            if (!TempData.Any())
            {
                TempData["Message"] = AuthenticationMessages.LoggedOut;
            }

            return RedirectToAction(controllerName: "home", actionName: "index");
        }
    }
}

LearningPlatform/LearningPlatform/Views/Authentication/Login.cshtml
@using LearningPlatform.Common.DTOs.ViewModels;
@model LoginViewModel
<br />
@{
    this.ViewData["Title"] = "Login";
    if (this.TempData.ContainsKey("Message"))
    {
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <div class="alert-success">
                <h5 class="mb-0">@this.TempData["Message"]</h5>
            </div>
        </div>
    }
}
<br />
<br />
<br />
<br />
<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
    <h6 class="section-title bg-white text-center text-primary px-3">Poodle e-LEARNING Platform</h6>
    <h1 class="mb-5">Login</h1>
</div>
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-4 justify-content-center">
            <!--Login Start-->
            <div class="col-lg-4 col-md-12 wow fadeInUp" data-wow-delay="0.5s">
                <form asp-controller="Authentication" asp-action="Login" method="Post">
                    <div class="row g-3">
                        <div class="col-12">
                            <div class="form-floating">
                                <input asp-for="Email" type="text" class="form-control" id="email" placeholder="Your Email">
                                <span asp-validation-for="Email" class="alert-danger"></span>
                                <label for="name">Email</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                <input asp-for="Password" type="password" class="form-control" id="password" placeholder="Password" onclick="myFunction()">
                                <span asp-validation-for="Password" class="alert-danger"></span>
                                <label for="name">Password</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <input class="btn btn-primary w-100 py-3" type="submit" value="Login">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!--Login End-->
<script>
    function myFunction() {
        var x = document.getElementById("password");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>
<br />
<br />
<br />
<br />
<br />

LearningPlatform/LearningPlatform/Views/Authentication/Register.cshtml
@using LearningPlatform.Common.DTOs.ViewModels;
@model RegisterViewModel
@{
    this.ViewData["Title"] = "Register";
}
<br />
<br />
<br />
<div class="text-center wow fadeInUp" data-wow-delay="0.1s">
    <h6 class="section-title bg-white text-center text-primary px-3">Poodle e-LEARNING Platform</h6>
    <h1 class="mb-5">Register</h1>
</div>
<!-- Service Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-4 justify-content-center">
            <!--Register Start-->
            <div class="col-lg-4 col-md-12 wow fadeInUp" data-wow-delay="0.5s">
                <form asp-controller="Authentication" asp-action="Register" method="Post">
                    <div class="row g-3">
                        <div class="col-12">
                            <div class="form-floating">
                                <input asp-for="Email" type="text" class="form-control" id="email" placeholder="Your Email">
                                <span asp-validation-for="Email" class="alert-danger"></span>
                                <label for="name">Email</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                <input asp-for="FirstName" type="text" class="form-control" id="firsName" placeholder="First Name">
                                <span asp-validation-for="FirstName" class="alert-danger"></span>
                                <label for="name">First Name</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                <input asp-for="LastName" type="text" class="form-control" id="lastName" placeholder="Last Name">
                                <span asp-validation-for="LastName" class="alert-danger"></span>
                                <label for="name">Last Name</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                <input asp-for="Password" type="password" class="form-control" id="password" placeholder="Password" onclick="myFunction()" />

                                <span asp-validation-for="Password" class="alert-danger"></span>
                                <label for="name">Password</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                <input asp-for="ConfirmPassword" type="password" class="form-control" id="password" placeholder="Confirm Password" onclick="myFunction()" />
                                <span asp-validation-for="ConfirmPassword" class="alert-danger"></span>
                                <label for="name">Confirm Password</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <input class="btn btn-primary w-100 py-3" type="submit" value="Register">
                        </div>
                    </div>
                </form>
            </div>
            <!--Register End-->
        </div>
    </div>
</div>
<!-- Service End -->
<script>
    function myFunction() {
        let passwordElements = document.querySelectorAll("#password");
        let passwordsArray = Array(...passwordElements);
        console.log(passwordElements);
        console.log(passwordsArray);
        passwordArray.forEach(function (value, 1, let))
        {
            if (element.type === "password") {
                element.type = "text";
            }
            else {
                element.type = "password";
            }
        }
    }
</script>